from __future__ import annotations

import argparse
import json
from pathlib import Path

from poe_affix_builder.adapters.poe2_source_repo import (
    POE2_REPO_BRANCH,
    POE2_REPO_URL,
    clone_poe2_repo as _clone_poe2_repo,
    resolve_mods_json_path as _resolve_mods_json_path,
)
from poe_affix_builder.builder import build_affixes, validate_mapping
from poe_affix_builder.poe2db_snapshot import refresh_snapshot
from poe_affix_builder.rebuild_mapping import rebuild_mapping


def _emit(message: str) -> None:
    print(message, flush=True)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="poe-affix-build")
    sub = parser.add_subparsers(dest="cmd", required=True)

    build = sub.add_parser("build", help="Build result/affixes JSON files from mods.json + mapping")
    build.add_argument("--source-dir", default="data/poe2/data", help="Folder containing mods.json")
    build.add_argument("--manifest", default="config/item_mapping.json", help="Path to mapping manifest JSON")
    build.add_argument("--out-dir", default="result/affixes", help="Output folder for item affix files")
    build.add_argument("--report", default="result/build_report.json", help="Path to build report JSON")

    validate = sub.add_parser("validate-mapping", help="Check mapping coverage against current mods.json")
    validate.add_argument("--source-dir", default="data/poe2/data", help="Folder containing mods.json")
    validate.add_argument("--manifest", default="config/item_mapping.json", help="Path to mapping manifest JSON")
    validate.add_argument("--out", default=None, help="Optional path to write validation report JSON")

    refresh = sub.add_parser("refresh-poe2db", help="Fetch poe2db snapshot from /us/Modifiers and item pages")
    refresh.add_argument("--snapshot", default="config/poe2db_snapshot.json", help="Output path for snapshot JSON")
    refresh.add_argument("--report", default="result/poe2db_refresh_report.json", help="Output path for refresh report JSON")
    refresh.add_argument("--index-url", default="https://poe2db.tw/us/Modifiers", help="poe2db modifiers index URL")

    rebuild = sub.add_parser("rebuild-mapping", help="Rebuild mapping from poe2db snapshot + mods.json")
    rebuild.add_argument("--source-dir", default="data/poe2/data", help="Folder containing mods.json")
    rebuild.add_argument("--snapshot", default="config/poe2db_snapshot.json", help="Snapshot path generated by refresh-poe2db")
    rebuild.add_argument("--out", default="config/item_mapping.json", help="Rebuilt mapping output path")
    rebuild.add_argument("--report", default="result/rebuild_mapping_report.json", help="Output path for rebuild report JSON")

    return parser


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()

    if args.cmd == "build":
        result = build_affixes(
            mods_json_path=_resolve_mods_json_path(Path(args.source_dir), emit=_emit),
            manifest_path=Path(args.manifest),
            out_dir=Path(args.out_dir),
            report_path=Path(args.report),
        )
        advisory_count = len(result.mapping_warnings)
        print(
            f"Built {result.items_written} files, {result.affixes_written} affixes, {result.tiers_written} tiers. "
            f"Unresolved tiers: {len(result.unresolved_tiers)}. "
            f"Coverage advisories: {advisory_count}",
        )
        return 0

    if args.cmd == "validate-mapping":
        report = validate_mapping(
            mods_json_path=_resolve_mods_json_path(Path(args.source_dir), emit=_emit),
            manifest_path=Path(args.manifest),
        )
        if args.out:
            out_path = Path(args.out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"Wrote validation advisory report to {out_path}")
        else:
            print(json.dumps(report, ensure_ascii=False, indent=2))
        return 0

    if args.cmd == "refresh-poe2db":
        report = refresh_snapshot(
            snapshot_path=Path(args.snapshot),
            report_path=Path(args.report),
            index_url=str(args.index_url),
        )
        print(
            f"Refreshed snapshot: {report['items_fetched']} items, "
            f"{report['affixes_fetched']} affixes, {report['tiers_fetched']} tiers"
        )
        return 0

    if args.cmd == "rebuild-mapping":
        result = rebuild_mapping(
            mods_json_path=_resolve_mods_json_path(Path(args.source_dir), emit=_emit),
            snapshot_path=Path(args.snapshot),
            out_path=Path(args.out),
            report_path=Path(args.report),
        )
        print(f"Rebuilt mapping: {result.items} items, {result.affixes} affixes, {result.tiers} tiers")
        return 0

    parser.print_help()
    return 1


__all__ = [
    "POE2_REPO_BRANCH",
    "POE2_REPO_URL",
    "_build_parser",
    "_clone_poe2_repo",
    "_resolve_mods_json_path",
    "main",
]


if __name__ == "__main__":
    raise SystemExit(main())
